version: "3.7"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: "userService"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d userService" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
  userservice:
    image: ovantsevich/userservice:latest
    ports:
      - "12345:12345"
    environment:
      - POSTGRES_DB_URL=postgres://postgres:postgres@host.docker.internal:5432/userService?sslmode=disable
      - JWT_KEY=874967EC3EA3490F8F2EF6478B72A756
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"